# Uncomment the next line to define a global platform for your project

# platform :ios, '11.0'

  
  use_frameworks!
  # Pods for RxSwift-MVVM

  target 'RxSwift-MVVM' do
      pod 'RxSwift', '6.2.0'
      pod 'RxCocoa', '6.2.0'
      pod 'SwiftyJSON'
  end


  # RxTest and RxBlocking make the most sense in the context of unit/integration tests
  target 'RxSwift-MVVMTests' do
      pod 'RxBlocking', '6.2.0'
      pod 'RxTest', '6.2.0'
  end

  target 'RxSwift-MVVMUITests' do
    # Pods for testing
  end
